server:
  port: 9501
#eureka:
#  client: # 客户端进行Eureka注册的配置
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://admin:enjoy@eureka1:7001/eureka

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka
  instance:
    instance-id: microcloud-zuul-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
spring:
  application:
    name: microcloud-zuul-gateway
  security:
    user:
      name: admin
      password: enjoy
zuul:
  routes:
    users:
      path: /users-proxy/**  #转换 把eureka上的服务名称换了
      serviceId: microcloud-provider-users
    users2:
      path: /users2-proxy/**
      url: http://localhost:8090/  #同serviceID 一个道理
    product:
      path: /product-proxy/**
      serviceId: microcloud-provider-product
  ignored-services:  #禁用serviceID
    "*"
  prefix: /enjoy-api  #强制在所有的url前加上例如： http://localhost:9501/enjoy-api/users-proxy/user/get/3