server:
  port: 7102
spring:
  application:
    name: microcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/malaian520/spingcloudconfig.git
eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka  #单个模式 下面的是eureka集群
      defaultZone: http://admin:enjoy@eureka3:7301/eureka
  instance:
    instance-id: microcloud-config2
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
